#!/bin/bash

packagelist=(
    libcap2-bin
    libsvm-dev
    libudev-dev
    libv4l-dev
    libpcl-dev
    libproj-dev
    python-catkin-tools
    python-pygraphviz
    python-rosinstall
    python-setuptools
    python-zmq
    python-gtk2
    python-gobject
    python-wxgtk2.8
    g++-multilib
    flex
    mongodb
    librealsense2
    librealsense2-dkms
    librealsense2-gl
    librealsense2-utils
    ros-kinetic-amcl
    ros-kinetic-bfl
    ros-kinetic-brics-actuator
    ros-kinetic-clear-costmap-recovery
    ros-kinetic-cob-scan-unifier
    ros-kinetic-cob-srvs
    ros-kinetic-dwa-local-planner
    ros-kinetic-dynamixel-controllers
    ros-kinetic-dynamixel-msgs
    ros-kinetic-eband-local-planner
    ros-kinetic-explore-lite
    ros-kinetic-frontier-exploration
    ros-kinetic-gazebo-ros-control
    ros-kinetic-gazebo-plugins
    ros-kinetic-gmapping
    ros-kinetic-urg-node
    ros-kinetic-joint-state-controller
    ros-kinetic-joy
    ros-kinetic-serial
    ros-kinetic-map-server
    ros-kinetic-move-base
    ros-kinetic-moveit-core
    ros-kinetic-moveit-commander
    ros-kinetic-moveit-msgs
    ros-kinetic-moveit-planners
    ros-kinetic-moveit-ros-move-group
    ros-kinetic-moveit-setup-assistant
    ros-kinetic-moveit-simple-controller-manager
    ros-kinetic-openni-launch
    ros-kinetic-openni2-launch
    ros-kinetic-pr2-dashboard-aggregator
    ros-kinetic-pr2-description
    ros-kinetic-pr2-msgs
    ros-kinetic-ros
    ros-kinetic-ros-controllers
    ros-kinetic-roslint
    ros-kinetic-rosmon
    ros-kinetic-rqt-robot-dashboard
    ros-kinetic-serial
    ros-kinetic-smach*
    ros-kinetic-srdfdom
    ros-kinetic-twist-mux
    ros-kinetic-usb-cam
    ros-kinetic-global-planner
    ros-kinetic-diagnostic-aggregator
    ros-kinetic-diagnostic-analysis
    ros-kinetic-laser-filters
    ros-kinetic-mongodb-store
    ros-kinetic-realsense2-camera
    ros-kinetic-robot-state-publisher
    ros-kinetic-gazebo-*
    bsdmainutils
    groff-base
    man-db
    libunistring0
    libasprintf0v5
    gettext-base
    gettext
    intltool-debian
    po-debconf
    libarchive-zip-perl
    libfile-stripnondeterminism-perl
    libtimedate-perl
    dh-strip-nondeterminism
    debhelper
    gir1.2-atk-1.0
    gir1.2-atspi-2.0
    gir1.2-freedesktop
    gir1.2-gdkpixbuf-2.0
    libpangoxft-1.0-0
    gir1.2-pango-1.0
    gir1.2-gtk-3.0
    libasprintf-dev
    libdbus-1-dev
    x11proto-record-dev
    libxtst-dev
    libatspi2.0-dev
    libatk-bridge2.0-dev
    libatk1.0-dev
    libcairo-script-interpreter2
    libpixman-1-dev
    libxcb-shm0-dev
    libcairo2-dev
    libepoxy-dev
    libgdk-pixbuf2.0-dev
    libgettextpo0
    libgettextpo-dev
    libglfw3
    libgmpxx4ldbl
    libgmp-dev
    libharfbuzz-icu0
    libharfbuzz-gobject0
    libharfbuzz-dev
    libpango1.0-dev
    x11proto-xinerama-dev
    libxinerama-dev
    x11proto-randr-dev
    libxrandr-dev
    libxcursor-dev
    x11proto-composite-dev
    libxcomposite-dev
    nettle-dev
    libgtk-3-dev
    libcanberra-gtk-module
    libcanberra-gtk3-module
    libsys-hostname-long-perl
    libmail-sendmail-perl
    bison
    libbison-dev
)

### install debian packages listed in array above

sudo apt-get update -qq
sudo apt-get install -y -qq ${packagelist[@]}
