#!/bin/bash

packagelist=(
    libcap2-bin
    libsvm-dev
    libudev-dev
    libv4l-dev
    libpcl-dev
    libproj-dev
    python-catkin-tools
    python-pygraphviz
    python-rosinstall
    python-setuptools
    python-zmq
    g++-multilib
    flex
    mongodb
    ros-melodic-amcl
    ros-melodic-bfl
    ros-melodic-brics-actuator
    ros-melodic-clear-costmap-recovery
    ros-melodic-cob-scan-unifier
    ros-melodic-cob-srvs
    ros-melodic-dwa-local-planner
    ros-melodic-dynamixel-workbench
    ros-melodic-gazebo-ros-control
    ros-melodic-gazebo-plugins
    ros-melodic-gmapping
    ros-melodic-urg-node
    ros-melodic-joint-state-controller
    ros-melodic-joy
    ros-melodic-serial
    ros-melodic-map-server
    ros-melodic-move-base
    ros-melodic-moveit-core
    ros-melodic-moveit-commander
    ros-melodic-moveit-msgs
    ros-melodic-moveit-planners
    ros-melodic-moveit-ros-move-group
    ros-melodic-moveit-setup-assistant
    ros-melodic-moveit-simple-controller-manager
    ros-melodic-openni-launch
    ros-melodic-openni2-launch
    ros-melodic-pr2-dashboard-aggregator
    ros-melodic-pr2-description
    ros-melodic-pr2-msgs
    ros-melodic-ros
    ros-melodic-ros-controllers
    ros-melodic-roslint
    ros-melodic-rosmon
    ros-melodic-rqt-robot-dashboard
    ros-melodic-serial
    ros-melodic-smach
    ros-melodic-smach-*
    ros-melodic-image-view
    ros-melodic-robot-state-publisher
    ros-melodic-joint-state-publisher
    ros-melodic-pr2-power-board
    ros-melodic-tf-conversions
    ros-melodic-srdfdom
    ros-melodic-twist-mux
    ros-melodic-usb-cam
    ros-melodic-global-planner
    ros-melodic-diagnostic-aggregator
    ros-melodic-diagnostic-analysis
    ros-melodic-laser-filters
    ros-melodic-mongodb-store
    ros-melodic-pcl-ros
    ros-melodic-pcl-conversions
    bsdmainutils
    groff-base
    man-db
    libasprintf0v5
    gettext-base
    gettext
    intltool-debian
    po-debconf
    libarchive-zip-perl
    libfile-stripnondeterminism-perl
    libtimedate-perl
    dh-strip-nondeterminism
    debhelper
    gir1.2-atk-1.0
    gir1.2-atspi-2.0
    gir1.2-freedesktop
    gir1.2-gdkpixbuf-2.0
    libpangoxft-1.0-0
    gir1.2-pango-1.0
    gir1.2-gtk-3.0
    libasprintf-dev
    libdbus-1-dev
    x11proto-record-dev
    libxtst-dev
    libatspi2.0-dev
    libatk-bridge2.0-dev
    libatk1.0-dev
    libcairo-script-interpreter2
    libpixman-1-dev
    libxcb-shm0-dev
    libcairo2-dev
    libepoxy-dev
    libgdk-pixbuf2.0-dev
    libgettextpo0
    libgettextpo-dev
    libglfw3
    libgmpxx4ldbl
    libgmp-dev
    libharfbuzz-icu0
    libharfbuzz-gobject0
    libharfbuzz-dev
    libpango1.0-dev
    x11proto-xinerama-dev
    libxinerama-dev
    x11proto-randr-dev
    libxrandr-dev
    libxcursor-dev
    x11proto-composite-dev
    libxcomposite-dev
    nettle-dev
    libgtk-3-dev
    libsys-hostname-long-perl
    libmail-sendmail-perl
    bison
    libbison-dev
)

### install debian packages listed in array above

sudo apt-get update -qq
sudo apt-get install -y -qq ${packagelist[@]}
